env:
  global:
    - CC_TEST_REPORTER_ID=8f35879f546b1f56e8b41581fc8086ab88031279e86e100f0d4ff79f6d41a826
    - DEP_VERSION=0.4.1

language: go
go:
  - master

install:

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - curl -L https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
  - dep ensure -vendor-only

script:
  - go test -coverprofile=c.out ./...

after_success:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
